version: "3"

services:
  myadminfortest:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    ports:
      - 8888:80
    depends_on:
      - mysql
    links:
      - mysql:db

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./conf.d/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      TZ: Asia/Shanghai

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d/Caddyfile:/etc/caddy/Caddyfile
      - ./:/var/www/html
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - php

  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  judge:
    container_name: judge
    build:
      context: .
      dockerfile: Dockerfile.judge.alpine
    volumes:
      - ./judge:/judge/judge
      - ./polygon:/judge/polygon
      # - ./libraries:/judge/libraries
    depends_on:
      - mysql
      - php
      - caddy
