name: PHPStan

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    name: "Static Analysis"

    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: "${{ matrix.php-version }}"
      - uses: php-actions/phpstan@master
        name: "Level 0 Check"
        with:
          path: assets/ commands/ components/ config/ controllers/ mail/ messages/ migrations/ models/ modules/ views/ web/ widgets/
          php_version: "${{ matrix.php-version }}"
          autoload_file: vendor/yiisoft/yii2/Yii.php
          memory_limit: 512M
          level: "0"
      - uses: php-actions/phpstan@master
        name: "Level 1 Check"
        continue-on-error: true
        with:
          path: assets/ commands/ components/ config/ controllers/ mail/ messages/ migrations/ models/ modules/ views/ web/ widgets/
          php_version: "${{ matrix.php-version }}"
          autoload_file: vendor/yiisoft/yii2/Yii.php
          memory_limit: 512M
          level: "1"
